<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<title>
    @yield('title')
</title>

<style>

*{
    box-sizing:border-box;
}

body{

    font-family: DejaVu Sans, sans-serif;

    margin:28px;

    color:#222;

    font-size:12px;

    line-height:1.45;

}

.header{

    width:100%;

    border-bottom:2px solid #1e3a8a;

    padding-bottom:14px;

    margin-bottom:18px;

}

.header-table{

    width:100%;

    border:none;

}

.header-table td{

    border:none;

    vertical-align:top;

    padding:0;

}

.company-name{

    font-size:24px;

    font-weight:bold;

    color:#1e3a8a;

}

.tagline{

    font-size:13px;

    color:#666;

    margin-top:4px;

}

.company-details{

    margin-top:8px;

    font-size:11px;

    color:#444;

    line-height:1.6;

}

.logo{

    text-align:right;

    width:140px;

}

.logo img{

    width:90px;

    height:auto;

}

.document-title{

    text-align:center;

    font-size:20px;

    font-weight:bold;

    color:#1e3a8a;

    margin:18px 0;

    text-transform:uppercase;

}

.section{

    margin-top:14px;

}

.table{

    width:100%;

    border-collapse:collapse;

}

.table td{

    border:1px solid #d6d6d6;

    padding:8px;

}

.label{

    width:35%;

    background:#f7f7f7;

    font-weight:bold;

}

.amount-box{

    margin-top:18px;

    border:2px solid #059669;

    text-align:center;

    padding:10px 12px;

}

.amount-title{

    font-size:11px;

    color:#666;

    text-transform:uppercase;

    letter-spacing:1px;

}

.amount{

    font-size:22px;

    font-weight:bold;

    color:#059669;

    margin-top:4px;

}

.footer{

    margin-top:30px;

    border-top:1px solid #ddd;

    padding-top:14px;

    font-size:11px;

    color:#666;

}

.signature{

    margin-top:30px;

    text-align:right;

}

.signature-line{

    width:180px;

    border-top:1px solid #333;

    margin-left:auto;

    margin-bottom:6px;

}

</style>

</head>

<body>

@php

$logoPath = null;

if(!empty($company->logo)){

    $candidate = storage_path('app/public/'.$company->logo);

    if(file_exists($candidate)){

        $logoPath = $candidate;

    }

}

@endphp

<div class="header">

<table class="header-table">

<tr>

<td>

<div class="company-name">

{{ $company->company_name }}

</div>

@if($company->company_tagline)

<div class="tagline">

{{ $company->company_tagline }}

</div>

@endif

<div class="company-details">

@if($company->address_line_1)

{{ $company->address_line_1 }}<br>

@endif

@if($company->address_line_2)

{{ $company->address_line_2 }}<br>

@endif

{{ collect([
$company->city,
$company->state,
$company->country,
$company->pincode,
])->filter()->implode(', ') }}

<br>


@if($company->whatsapp)

WhatsApp : {{ $company->whatsapp }}<br>

@endif


@if($company->website)

Website : {{ $company->website }}<br>

@endif


@if($company->pan_number)

PAN : {{ $company->pan_number }}

@endif

</div>

</td>

<td class="logo">

    @if($logoPath)

        <img
            src="{{ $logoPath }}"
            style="width:90px;height:auto;"
        >

    @endif

    @isset($qrCode)

        <div style="margin-top:12px;">

            <img
    src="data:image/svg+xml;base64,{{ $qrCode }}"
    style="width:82px;height:82px;"
>

            <div
                style="
                    font-size:9px;
                    color:#555;
                    margin-top:4px;
                    font-weight:bold;
                "
            >
                Scan to Verify
            </div>

        </div>

    @endisset

</td>
</tr>

</table>

</div>

<div class="document-title">

@yield('document-title')

</div>

@yield('content')

<div class="footer">

<div style="text-align:center;">

    <strong>

        Thank you for your business.

    </strong>

    <br><br>

    This receipt is an official electronic acknowledgement of the payment received by

    <strong>{{ $company->company_name }}</strong>.

    <br><br>

    This document has been digitally generated by Jaipur Digital Agency and is valid without a handwritten signature or company seal.

    <br><br>

    <strong>Need Assistance?</strong>

    <br>

    Email:
    {{ $company->email }}

    &nbsp;&nbsp;|&nbsp;&nbsp;

    Phone:
    {{ $company->phone }}

    @if($company->website)

        <br>

        Website:
        {{ $company->website }}

    @endif

    <br><br>

    © {{ date('Y') }}
    {{ $company->company_name }}.
    All Rights Reserved.

</div>

</div>

</body>

</html>