<!DOCTYPE html>
<html>
<head>
    <title>Receipt Verification</title>

    <style>

        body{
            font-family:Arial,sans-serif;
            max-width:700px;
            margin:50px auto;
            padding:20px;
        }

        .success{
            color:#15803d;
            font-size:30px;
            font-weight:bold;
        }

        table{
            width:100%;
            border-collapse:collapse;
            margin-top:30px;
        }

        td{
            border:1px solid #ddd;
            padding:12px;
        }

        td:first-child{
            width:35%;
            font-weight:bold;
            background:#f5f5f5;
        }

    </style>

</head>

<body>

<div class="success">
    ✓ Receipt Verified
</div>

<p>
This receipt was generated by your AgencyOS system.
</p>

<table>

<tr>
    <td>Receipt Number</td>
    <td>{{ $payment->receipt_number }}</td>
</tr>

<tr>
    <td>Payment Number</td>
    <td>{{ $payment->payment_no }}</td>
</tr>

<tr>
    <td>Quotation</td>
    <td>{{ $payment->quotation->quotation_code }}</td>
</tr>

<tr>
    <td>Customer</td>
    <td>{{ $payment->customer->display_name }}</td>
</tr>

<tr>
    <td>Amount</td>
    <td>₹ {{ number_format($payment->amount,2) }}</td>
</tr>

<tr>
    <td>Payment Date</td>
    <td>{{ optional($payment->payment_date)->format('d M Y') }}</td>
</tr>

</table>

</body>
</html>